# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from datetime import date

class Ui_AddOrder(object):

    def __init__(self):
        # PostgreSQL connection        
        self.conn = psycopg2.connect(host="aws-0-ap-southeast-1.pooler.supabase.com", dbname="postgres", user="postgres.oxzprkjuxnjgnfihweyj", 
                                     password="Milliondollarbaby123", port=6543)
        self.cur = self.conn.cursor()

    def add_new_order(self):
        # Get data from UI elements
        cus_fname = self.lineEdit.text()
        cus_lname = self.LnamelineEdit.text()
        cus_email = self.emailLineEdit.text()
        cus_phone = self.phonelineEdit.text()
        cus_address = self.AddressLineEdit.text()
        order_date = date.today()
        due_date = self.dueDateEdit.text()
        product_category = self.comboBox.currentText()
        product_name = self.prodNameLineEdit.text()
        quantity = self.QuantityLineEdit.text()
        total_amount = self.TotalLineEdit.text()

        # Validate input data
        if not (cus_fname and cus_lname and cus_email and cus_phone and cus_address and 
                due_date and product_category and product_name and quantity and total_amount):
            self.show_message("Error", "Please fill all the fields.")
            return

        try:
            # Check if product exists and get its ID
            sql_get_product_id = "SELECT PROD_ID FROM PRODUCT WHERE PROD_NAME = %s"
            self.cur.execute(sql_get_product_id, (product_name,))
            product_id_result = self.cur.fetchone()

            if product_id_result is None:
                self.show_message("Error", "Selected product does not exist.")
                return

            product_id = product_id_result[0]

            # Insert into CUSTOMER table
            sql_customer = """
            INSERT INTO CUSTOMER (CUS_FNAME, CUS_LNAME, CUS_EMAIL, CUS_PHONE, CUS_ADDRESS) 
            VALUES (%s, %s, %s, %s, %s) RETURNING CUS_CODE
            """
            self.cur.execute(sql_customer, (cus_fname, cus_lname, cus_email, cus_phone, cus_address))
            customer_id = self.cur.fetchone()[0]  # Get the newly inserted customer ID

            # Insert into ORDERS table
            sql_orders = """
            INSERT INTO ORDERS (CUS_CODE, ORD_DATE, ORD_DATE_COMPLETION, PROD_ID, ORD_QUANTITY, ORD_TOTAL_AMOUNT) 
            VALUES (%s, %s, %s, %s, %s, %s)
            """
            self.cur.execute(sql_orders, (customer_id, order_date, due_date, product_id, quantity, total_amount))

            self.conn.commit()
            self.show_message("Success", "Data saved successfully.")
        except psycopg2.Error as e:
            self.conn.rollback()  # Roll back transaction on error
            error_message = f"Error saving data: {e.pgcode} - {e.pgerror}"
            self.show_message("Error", error_message) 

    def show_message(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Information)
        msg.exec_()

    def setupUi(self, AddOrder):
        AddOrder.setObjectName("AddOrder")
        AddOrder.resize(641, 481)
        AddOrder.setFixedSize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        AddOrder.setSizePolicy(sizePolicy)
        self.frame = QtWidgets.QFrame(AddOrder)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
                                "    background-color: rgb(255, 255, 255);\n"
                                "}\n"
                                "QLabel#AddOrder{\n"
                                "    font-size: 25px;\n"
                                "}\n"
                                "QLineEdit{\n"
                                "    width: 200px;\n"
                                "}\n"
                                "QPushButton#Cancel{    \n"
                                "    color: rgb(255, 255, 255);\n"
                                "    background-color: #202020;\n"
                                "}\n"
                                "QPushButton{    \n"
                                "    color: rgb(255, 255, 255);\n"
                                "    background-color: #CD2E2E;\n"
                                "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(240, 10, 126, 26))
        self.AddOrder.setObjectName("AddOrder")

        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.clicked.connect(AddOrder.close)
        self.Cancel.setGeometry(QtCore.QRect(380, 370, 96, 31))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        font_cancel = QtGui.QFont()
        font_cancel.setFamily("Arial")
        font_cancel.setPointSize(10)
        font_cancel.setBold(True)        
        self.Cancel.setFont(font_cancel)
        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddOrder_3.clicked.connect(self.add_new_order)
        self.AddOrder_3.setGeometry(QtCore.QRect(490, 370, 91, 31))
        self.AddOrder_3.setObjectName("AddOrder_3")
        font_AddOrder_3 = QtGui.QFont()
        font_AddOrder_3.setFamily("Arial")
        font_AddOrder_3.setPointSize(10)
        font_AddOrder_3.setBold(True)        
        self.AddOrder_3.setFont(font_cancel)
        
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(50, 50, 521, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.Cancel.raise_()
        self.AddOrder_3.raise_()

        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 111, 20))
        self.lineEdit.setMaxLength(300)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label.setObjectName("label")

        self.LnamelineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.LnamelineEdit.setGeometry(QtCore.QRect(30, 80, 111, 20))
        self.LnamelineEdit.setMaxLength(300)
        self.LnamelineEdit.setObjectName("LnamelineEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.label_5.setObjectName("label_5")

        self.emailLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.emailLineEdit.setGeometry(QtCore.QRect(30, 130, 113, 20))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 76, 16))
        self.label_2.setObjectName("label_2")

        self.phonelineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.phonelineEdit.setGeometry(QtCore.QRect(30, 180, 113, 20))
        self.phonelineEdit.setObjectName("phonelineEdit")
        self.phoneLineLabel = QtWidgets.QLabel(self.frame_2)
        self.phoneLineLabel.setGeometry(QtCore.QRect(30, 160, 81, 16))
        self.phoneLineLabel.setObjectName("phoneLineLabel")

        self.AddressLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.AddressLineEdit.setGeometry(QtCore.QRect(30, 230, 113, 20))
        self.AddressLineEdit.setObjectName("AddressLineEdit")
        self.addressLabel = QtWidgets.QLabel(self.frame_2)
        self.addressLabel.setGeometry(QtCore.QRect(30, 210, 76, 16))
        self.addressLabel.setObjectName("addressLabel")

        self.priceLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.priceLineEdit.setEnabled(False)
        self.priceLineEdit.setGeometry(QtCore.QRect(30, 280, 113, 20))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.priceLabel = QtWidgets.QLabel(self.frame_2)
        self.priceLabel.setGeometry(QtCore.QRect(30, 260, 76, 16))
        self.priceLabel.setObjectName("priceLabel")

        self.TotalLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TotalLineEdit.setGeometry(QtCore.QRect(30, 330, 113, 20))
        self.TotalLineEdit.setObjectName("TotalLineEdit")
        self.totalAmtLabel = QtWidgets.QLabel(self.frame_2)
        self.totalAmtLabel.setGeometry(QtCore.QRect(30, 310, 76, 16))
        self.totalAmtLabel.setObjectName("totalAmtLabel")

        self.dueDateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dueDateEdit.setGeometry(QtCore.QRect(330, 30, 113, 22))
        self.dueDateEdit.setCalendarPopup(True)
        self.dueDateEdit.setObjectName("dueDateEdit")
        self.dueDateEdit.setDate(QtCore.QDate.currentDate())  

        self.dueDateLabel = QtWidgets.QLabel(self.frame_2)
        self.dueDateLabel.setGeometry(QtCore.QRect(330, 10, 47, 14))
        self.dueDateLabel.setObjectName("dueDateLabel")
        self.dueDateLabel.setText("Due Date") 


        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(330, 80, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.categoryLabel = QtWidgets.QLabel(self.frame_2)
        self.categoryLabel.setGeometry(QtCore.QRect(330, 60, 81, 16))
        self.categoryLabel.setObjectName("categoryLabel")

        self.prodNameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.prodNameLineEdit.setGeometry(QtCore.QRect(330, 130, 151, 22))
        self.prodNameLineEdit.setObjectName("prodNameLineEdit")
        self.prodNameLabel = QtWidgets.QLabel(self.frame_2)
        self.prodNameLabel.setGeometry(QtCore.QRect(330, 110, 81, 16))
        self.prodNameLabel.setObjectName("prodNameLabel")

        self.QuantityLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.QuantityLineEdit.setGeometry(QtCore.QRect(330, 180, 113, 20))
        self.QuantityLineEdit.setObjectName("QuantityLineEdit")
        self.quantityLabel = QtWidgets.QLabel(self.frame_2)
        self.quantityLabel.setGeometry(QtCore.QRect(330, 160, 47, 14))
        self.quantityLabel.setObjectName("quantityLabel")

        self.sizeLineEdit1 = QtWidgets.QLineEdit(self.frame_2)
        self.sizeLineEdit1.setGeometry(QtCore.QRect(330, 230, 41, 20))
        self.sizeLineEdit1.setObjectName("sizeLineEdit1")
        self.sizeLabel = QtWidgets.QLabel(self.frame_2)
        self.sizeLabel.setGeometry(QtCore.QRect(330, 210, 47, 14))
        self.sizeLabel.setObjectName("sizeLabel")

        self.sizeLineEdit2 = QtWidgets.QLineEdit(self.frame_2)
        self.sizeLineEdit2.setGeometry(QtCore.QRect(400, 230, 41, 20))
        self.sizeLineEdit2.setObjectName("sizeLineEdit2")
        
        self.comboBox_unitMeasure = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_unitMeasure.setGeometry(QtCore.QRect(450, 230, 61, 22))
        self.comboBox_unitMeasure.setObjectName("comboBox_unitMeasure")
        self.comboBox_unitMeasure.addItem("")
        self.comboBox_unitMeasure.addItem("")
        self.comboBox_unitMeasure.addItem("")
        self.comboBox_unitMeasure.addItem("")
        self.comboBox_unitMeasure.addItem("")

        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(378, 230, 21, 41))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        
        AddOrder.setTabOrder(self.lineEdit, self.LnamelineEdit)
        AddOrder.setTabOrder(self.LnamelineEdit, self.emailLineEdit)
        AddOrder.setTabOrder(self.emailLineEdit, self.phonelineEdit)
        AddOrder.setTabOrder(self.phonelineEdit, self.AddressLineEdit)
        AddOrder.setTabOrder(self.AddressLineEdit, self.priceLineEdit)
        AddOrder.setTabOrder(self.priceLineEdit, self.TotalLineEdit)
        AddOrder.setTabOrder(self.TotalLineEdit, self.dueDateEdit)
        AddOrder.setTabOrder(self.dueDateEdit, self.comboBox)
        AddOrder.setTabOrder(self.comboBox, self.prodNameLineEdit)
        AddOrder.setTabOrder(self.prodNameLineEdit, self.QuantityLineEdit)
        AddOrder.setTabOrder(self.QuantityLineEdit, self.sizeLineEdit1)
        AddOrder.setTabOrder(self.sizeLineEdit1, self.sizeLineEdit2)
        AddOrder.setTabOrder(self.sizeLineEdit2, self.comboBox_unitMeasure)
        AddOrder.setTabOrder(self.comboBox_unitMeasure, self.AddOrder_3)
        AddOrder.setTabOrder(self.AddOrder_3, self.Cancel)

        self.retranslateUi(AddOrder)
        QtCore.QMetaObject.connectSlotsByName(AddOrder)

    def retranslateUi(self, AddOrder):
        _translate = QtCore.QCoreApplication.translate
        AddOrder.setWindowTitle(_translate("AddOrder", "Dialog"))
        self.AddOrder.setText(_translate("AddOrder", "Add Order"))
        self.Cancel.setText(_translate("AddOrder", "Cancel"))
        self.AddOrder_3.setText(_translate("AddOrder", "Add Order"))
        self.addressLabel.setText(_translate("AddOrder", "Address"))
        self.priceLabel.setText(_translate("AddOrder", "Price"))
        self.sizeLabel.setText(_translate("AddOrder", "Size"))
        self.quantityLabel.setText(_translate("AddOrder", "Quantity"))
        self.categoryLabel.setText(_translate("AddOrder", "Category"))
        self.dueDateLabel.setText(_translate("AddOrder", "Due Date"))
        self.comboBox.setItemText(0, _translate("AddOrder", "Large Format Tarpaulin"))
        self.comboBox.setItemText(1, _translate("AddOrder", "Vinyl Sticker Printing"))
        self.comboBox.setItemText(2, _translate("AddOrder", "Laser Printing Stickers"))
        self.comboBox.setItemText(3, _translate("AddOrder", "T-shirt Printing"))
        self.prodNameLabel.setText(_translate("AddOrder", "Type of Product"))
        self.phoneLineLabel.setText(_translate("AddOrder", "Contact Number"))
        self.label.setText(_translate("AddOrder", "Customer First Name"))
        self.label_5.setText(_translate("AddOrder", "Customer Last Name"))
        self.label_2.setText(_translate("AddOrder", "Email Address"))
        self.totalAmtLabel.setText(_translate("AddOrder", "Total Amount"))
        self.textEdit.setHtml(_translate("AddOrder", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.comboBox_unitMeasure.setItemText(0, _translate("AddOrder", "ft"))
        self.comboBox_unitMeasure.setItemText(1, _translate("AddOrder", "inches"))
        self.comboBox_unitMeasure.setItemText(2, _translate("AddOrder", "small"))
        self.comboBox_unitMeasure.setItemText(3, _translate("AddOrder", "medium"))
        self.comboBox_unitMeasure.setItemText(4, _translate("AddOrder", "large"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddOrder = QtWidgets.QDialog()
    ui = Ui_AddOrder()
    ui.setupUi(AddOrder)
    AddOrder.show()
    sys.exit(app.exec_())
