import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 481)
        Dialog.setMinimumSize(QtCore.QSize(641, 481))
        Dialog.setMaximumSize(QtCore.QSize(641, 481))
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel#AddOrder{\n"
"    font-size: 25px;\n"
"}\n"
"QLineEdit{\n"
"    width: 200px;\n"
"}\n"
"QPushButton#Cancel{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #202020;\n"
"}\n"
"QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #CD2E2E;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(240, 10, 126, 26))
        self.AddOrder.setObjectName("AddOrder")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(360, 420, 96, 31))
        self.Cancel.setObjectName("Cancel")
        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.setGeometry(QtCore.QRect(470, 420, 91, 31))
        self.AddOrder_3.setObjectName("AddOrder_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(50, 50, 521, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(30, 230, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(30, 210, 76, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 280, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 76, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(330, 280, 41, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(330, 260, 47, 14))
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(330, 230, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(330, 210, 47, 14))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(330, 110, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(330, 60, 47, 14))
        self.label_10.setObjectName("label_10")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(330, 80, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(330, 10, 61, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(330, 30, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(330, 130, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(330, 180, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(330, 160, 81, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 180, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 130, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 111, 20))
        self.lineEdit.setMaxLength(300)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 80, 111, 20))
        self.lineEdit_5.setMaxLength(300)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 76, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 76, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(30, 330, 113, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(400, 280, 41, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(378, 280, 21, 41))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_3.setGeometry(QtCore.QRect(450, 280, 61, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textEdit.raise_()
        self.lineEdit_14.raise_()
        self.label_14.raise_()
        self.lineEdit_4.raise_()
        self.label_4.raise_()
        self.lineEdit_10.raise_()
        self.label_11.raise_()
        self.lineEdit_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_10.raise_()
        self.lineEdit_13.raise_()
        self.label_9.raise_()
        self.lineEdit_9.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label_15.raise_()
        self.lineEdit_3.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.lineEdit_5.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_12.raise_()
        self.comboBox_3.raise_()
        self.frame_2.raise_()
        self.AddOrder.raise_()
        self.Cancel.raise_()
        self.AddOrder_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AddOrder.setText(_translate("Dialog", "Add Order"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.AddOrder_3.setText(_translate("Dialog", "Add Order"))
        self.label_14.setText(_translate("Dialog", "Address"))
        self.label_4.setText(_translate("Dialog", "Price"))
        self.label_11.setText(_translate("Dialog", "Size"))
        self.label_12.setText(_translate("Dialog", "Quantity"))
        self.label_13.setText(_translate("Dialog", "Type of Product"))
        self.label_10.setText(_translate("Dialog", "Due Date"))
        self.label_9.setText(_translate("Dialog", "Order Date"))
        self.comboBox.setItemText(0, _translate("Dialog", "Large Format Tarpaulin"))
        self.comboBox.setItemText(1, _translate("Dialog", "Vinyl Sticker Printing"))
        self.comboBox.setItemText(2, _translate("Dialog", "Laser Printing Stickers"))
        self.comboBox.setItemText(3, _translate("Dialog", "T-shirt Printing"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Tarpaulin"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Sticker"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Business Card"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Brochure"))
        self.label_15.setText(_translate("Dialog", "Category"))
        self.label_3.setText(_translate("Dialog", "Contact Number"))
        self.label.setText(_translate("Dialog", "Customer First Name"))
        self.label_5.setText(_translate("Dialog", "Customer Last Name"))
        self.label_2.setText(_translate("Dialog", "Email Address"))
        self.label_6.setText(_translate("Dialog", "Total Amount"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "ft"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "inches"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "small"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "medium"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "large"))

    def insert_data_to_db(self):
        # Connect to the database
        try:
            conn = psycopg2.connect(host="localhost", dbname="MCAV", user="postgres", password="1234", port=5432)
            cursor = conn.cursor()
        except psycopg2.Error as e:
            print("Error connecting to PostgreSQL database:", e)
            return

        # Extract data from fields
        first_name = self.lineEdit.text()
        last_name = self.lineEdit_5.text()
        email = self.lineEdit_2.text()
        contact_number = self.lineEdit_3.text()
        address = self.lineEdit_14.text()
        price = self.lineEdit_4.text()
        size = self.lineEdit_10.text()
        quantity = self.lineEdit_11.text()
        order_date = self.lineEdit_9.text()
        due_date = self.lineEdit_13.text()
        product_type = self.comboBox.currentText()
        category = self.comboBox_2.currentText()
        total_amount = self.lineEdit_15.text()

        # Insert data into the database
        try:
            cursor.execute("""
                INSERT INTO CUSTOMER (CUS_FNAME, CUS_LNAME, CUS_EMAIL, CUS_PHONE, CUS_ADDRESS)
                VALUES (%s, %s, %s, %s, %s)
            """, (first_name, last_name, email, contact_number, address))
            conn.commit()
            print("Data inserted successfully.")
        except psycopg2.Error as e:
            print("Error inserting data into PostgreSQL database:", e)
            conn.rollback()
        finally:
            # Close the cursor and connection
            cursor.close()
            conn.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    
    # Connect the button's clicked signal to the insert_data_to_db method
    ui.AddOrder_3.clicked.connect(ui.insert_data_to_db)
    
    Dialog.show()
    sys.exit(app.exec_())
