# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPurchase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from datetime import date
import psycopg2


class Ui_AddPurchase(object):

    def __init__(self):
        # PostgreSQL connection
        self.conn = psycopg2.connect(host="aws-0-ap-southeast-1.pooler.supabase.com", dbname="postgres", user="postgres.oxzprkjuxnjgnfihweyj", 
                                     password="Milliondollarbaby123", port=6543)
        self.cur = self.conn.cursor()

    def save_data(self):
        # Get data from UI elements
        sup_name = self.lineEdit.text().strip()
        sup_email = self.emailLineEdit.text().strip()
        sup_contact = self.contactLineEdit.text().strip()
        sup_address = self.addressLineEdit.text().strip()
        sup_country = self.country.text().strip()
        pur_total = self.totalLineEdit.text().strip()        
        pur_order_date = self.orderDateEdit.date().toString(QtCore.Qt.ISODate)
        pur_product_name = self.comboBox.currentText().strip()
        pur_quantity = self.QuantityLineEdit.text().strip()
        pur_thickness = self.prodNameLineEdit.text().strip()
        pur_roll_size = self.TotalLineEdit.text().strip()

        # Validate input data
        if not all([sup_name and sup_contact and sup_address and sup_email and pur_total and 
                    sup_country and pur_order_date and pur_product_name and pur_quantity]):
            missing_fields = []
            if not sup_name:
                missing_fields.append("Supplier Name")
            if not sup_email:
                missing_fields.append("Supplier Email")                
            if not sup_contact:
                missing_fields.append("Supplier Contact")
            if not sup_address:
                missing_fields.append("Supplierr Address")
            if not sup_country:
                missing_fields.append("Supplier Country")                
            if not pur_total:
                missing_fields.append("Total Amount")
            if not pur_order_date:
                missing_fields.append("Order Date")
            if not pur_product_name:
                missing_fields.append("Product Name")
            if not pur_quantity:
                missing_fields.append("Quantity")   

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText(f"Please input all required fields:\n{', '.join(missing_fields)}")
            msg.setWindowTitle("Required Fields")
            msg.exec_()
            return

        confirm_msg = QMessageBox()
        confirm_msg.setIcon(QMessageBox.Question)
        confirm_msg.setText("Add to Purchase list?")
        confirm_msg.setWindowTitle("Confirmation")
        confirm_msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)

        result = confirm_msg.exec_() 

        if result == QMessageBox.Yes:
            # Insert into SUPPLIER table
            try:
                sql_supplier = """
                INSERT INTO SUPPLIER (SUP_NAME, SUP_EMAIL, SUP_CONTACT, SUP_ADDRESS, SUP_COUNTRY) 
                VALUES (%s, %s, %s, %s, %s) 
                """
                self.cur.execute(sql_supplier, (sup_name, sup_email, sup_contact, sup_address, sup_country))

                # Insert into PURCHASE table
                sql_purchase = """
                INSERT INTO PURCHASE (PUR_AMOUNT, PUR_ORDER_DATE, PUR_PRODUCT_NAME, PUR_QUANTITY, PUR_THICKNESS, PUR_ROLL_SIZE) 
                VALUES (%s, %s, %s, %s, %s, %s)
                """

                self.cur.execute(sql_purchase, (pur_total, pur_order_date, pur_product_name, pur_quantity, pur_thickness, pur_roll_size))
                self.conn.commit()
                self.show_message("Success", "Data saved successfully.")
            except psycopg2.Error as e:
                self.conn.rollback()  # Roll back transaction on error
                error_message = f"Error saving data: {e.pgcode} - {e.pgerror}"
                self.show_message("Error", error_message)  

    def show_message(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Information)
        msg.exec_()

    def setupUi(self, AddPurchase):
        AddPurchase.setObjectName("AddPurchase")
        AddPurchase.resize(640, 480)
        self.frame = QtWidgets.QFrame(AddPurchase)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
                                "    background-color: rgb(255, 255, 255);\n"
                                "}\n"
                                "QLabel#AddOrder{\n"
                                "    font-size: 25px;\n"
                                "}\n"
                                "QLineEdit{\n"
                                "    width: 200px;\n"
                                "}\n"
                                "QPushButton#Cancel{    \n"
                                "    color: rgb(255, 255, 255);\n"
                                "    background-color: #202020;\n"
                                "}\n"
                                "QPushButton{    \n"
                                "    color: rgb(255, 255, 255);\n"
                                "    background-color: #CD2E2E;\n"
                                "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(35, 30, 161, 26))
        self.AddOrder.setObjectName("AddOrder")

        self.searchLineEdit = QtWidgets.QLineEdit(self.frame)
        self.searchLineEdit.setGeometry(QtCore.QRect(80, 90, 111, 20))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchLabel = QtWidgets.QLabel(self.frame)
        self.searchLabel.setGeometry(QtCore.QRect(80, 70, 111, 16))
        self.searchLabel.setObjectName("searchLabel")

        # Search Button
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setObjectName("searchButton")
        font_search = QtGui.QFont()
        font_search.setFamily("Arial")
        font_search.setPointSize(8)
        font_search.setBold(True)
        self.searchButton.setFont(font_search) 

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 120, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 140, 111, 20))
        self.lineEdit.setMaxLength(300)
        self.lineEdit.setObjectName("lineEdit")

        self.emailLineEdit = QtWidgets.QLineEdit(self.frame)
        self.emailLineEdit.setGeometry(QtCore.QRect(80, 195, 113, 20))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.emailLabel = QtWidgets.QLabel(self.frame)
        self.emailLabel.setGeometry(QtCore.QRect(80, 175, 76, 16))
        self.emailLabel.setObjectName("emailLabel")

        self.contactLineEdit = QtWidgets.QLineEdit(self.frame)
        self.contactLineEdit.setGeometry(QtCore.QRect(80, 250, 113, 20))
        self.contactLineEdit.setObjectName("contactLineEdit")
        self.contactLabel = QtWidgets.QLabel(self.frame)
        self.contactLabel.setGeometry(QtCore.QRect(80, 230, 81, 16))
        self.contactLabel.setObjectName("contactLabel")

        self.addressLabel = QtWidgets.QLabel(self.frame)
        self.addressLabel.setGeometry(QtCore.QRect(80, 280, 76, 16))
        self.addressLabel.setObjectName("addressLabel")
        self.addressLineEdit = QtWidgets.QLineEdit(self.frame)
        self.addressLineEdit.setGeometry(QtCore.QRect(80, 300, 113, 20))
        self.addressLineEdit.setObjectName("addressLineEdit")

        self.countryLabel = QtWidgets.QLabel(self.frame)
        self.countryLabel.setGeometry(QtCore.QRect(80, 340, 76, 16))
        self.countryLabel.setObjectName("countryLabel")
        self.countryLineEdit = QtWidgets.QLineEdit(self.frame)
        self.countryLineEdit.setGeometry(QtCore.QRect(80, 360, 113, 20))
        self.countryLineEdit.setObjectName("countryLineEdit")

        self.totalLineEdit = QtWidgets.QLineEdit(self.frame)
        self.totalLineEdit.setGeometry(QtCore.QRect(405, 90, 113, 20))
        self.totalLineEdit.setObjectName("totalLineEdit")
        self.totalLabel = QtWidgets.QLabel(self.frame)
        self.totalLabel.setGeometry(QtCore.QRect(405, 70, 66, 16))
        self.totalLabel.setObjectName("totalLabel")

        self.orderDateEdit = QtWidgets.QDateEdit(self.frame)
        self.orderDateEdit.setGeometry(QtCore.QRect(405, 140, 113, 20))
        self.orderDateEdit.setCalendarPopup(True)
        self.orderDateEdit.setObjectName("orderDateEdit")
        self.orderDateEdit.setDate(QtCore.QDate.currentDate())
        self.orderDateLabel = QtWidgets.QLabel(self.frame)
        self.orderDateLabel.setGeometry(QtCore.QRect(405, 120, 66, 16))
        self.orderDateLabel.setObjectName("orderDateLabel")

        self.prodNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.prodNameLineEdit.setGeometry(QtCore.QRect(405, 195, 113, 20))
        self.prodNameLineEdit.setObjectName("prodNameLineEdit")
        self.product_Label = QtWidgets.QLabel(self.frame)
        self.product_Label.setGeometry(QtCore.QRect(405, 175, 81, 16))
        self.product_Label.setObjectName("product_Label")

        self.quantityLineEdit = QtWidgets.QLineEdit(self.frame)
        self.quantityLineEdit.setGeometry(QtCore.QRect(405, 300, 113, 20))
        self.quantityLineEdit.setObjectName("quantityLineEdit")
        self.quantityLabel = QtWidgets.QLabel(self.frame)
        self.quantityLabel.setGeometry(QtCore.QRect(405, 280, 86, 16))
        self.quantityLabel.setObjectName("quantityLabel")

        self.rollsizeLabel = QtWidgets.QLabel(self.frame)
        self.rollsizeLabel.setGeometry(QtCore.QRect(405, 340, 47, 14))
        self.rollsizeLabel.setObjectName("rollsizeLabel")
        self.rollsizeLineEdit1 = QtWidgets.QLineEdit(self.frame)
        self.rollsizeLineEdit1.setGeometry(QtCore.QRect(405, 360, 113, 20))
        self.rollsizeLineEdit1.setObjectName("rollsizeLineEdit1")

        self.thicknessLineEdit = QtWidgets.QLineEdit(self.frame)
        self.thicknessLineEdit.setGeometry(QtCore.QRect(405, 250, 113, 20))
        self.thicknessLineEdit.setObjectName("thicknessLineEdit")
        self.thicknessLabel = QtWidgets.QLabel(self.frame)
        self.thicknessLabel.setGeometry(QtCore.QRect(405, 230, 81, 16))
        self.thicknessLabel.setObjectName("thicknessLabel")

        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.clicked.connect(AddPurchase.close)
        self.Cancel.setGeometry(QtCore.QRect(370, 410, 96, 31))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        font_Cancel = QtGui.QFont()
        font_Cancel.setFamily("Arial")
        font_Cancel.setPointSize(9)
        font_Cancel.setBold(True)
        self.Cancel.setFont(font_Cancel) 

        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.clicked.connect(self.save_data)
        self.AddOrder_3.setGeometry(QtCore.QRect(480, 410, 100, 31))
        self.AddOrder_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddOrder_3.setObjectName("AddOrder_3")
        font_add = QtGui.QFont()
        font_add.setFamily("Arial")
        font_add.setPointSize(9)
        font_add.setBold(True)
        self.AddOrder_3.setFont(font_add) 

        self.retranslateUi(AddPurchase)
        QtCore.QMetaObject.connectSlotsByName(AddPurchase)

        # Set tab order
        AddPurchase.setTabOrder(self.searchLineEdit, self.searchButton)
        AddPurchase.setTabOrder(self.searchButton, self.lineEdit)
        AddPurchase.setTabOrder(self.lineEdit, self.emailLineEdit)
        AddPurchase.setTabOrder(self.emailLineEdit, self.contactLineEdit)
        AddPurchase.setTabOrder(self.contactLineEdit, self.addressLineEdit)
        AddPurchase.setTabOrder(self.addressLineEdit, self.countryLineEdit)
        AddPurchase.setTabOrder(self.countryLineEdit, self.totalLineEdit)
        AddPurchase.setTabOrder(self.totalLineEdit, self.orderDateEdit)
        AddPurchase.setTabOrder(self.orderDateEdit, self.prodNameLineEdit)
        AddPurchase.setTabOrder(self.prodNameLineEdit, self.thicknessLineEdit)
        AddPurchase.setTabOrder(self.thicknessLineEdit, self.quantityLineEdit)
        AddPurchase.setTabOrder(self.quantityLineEdit, self.rollsizeLineEdit1)
        AddPurchase.setTabOrder(self.rollsizeLineEdit1, self.Cancel)
        AddPurchase.setTabOrder(self.Cancel, self.AddOrder_3)

    def retranslateUi(self, AddPurchase):
        _translate = QtCore.QCoreApplication.translate
        AddPurchase.setWindowTitle(_translate("AddPurchase", "Add Purchase"))
        self.AddOrder.setText(_translate("AddPurchase", "Add Purchase"))
        self.searchLabel.setText(_translate("AddPurchase", "Search Supplier ID"))
        self.searchButton.setText(_translate("AddPurchase", "Search"))
        self.label.setText(_translate("AddPurchase", "Supplier Name"))
        self.emailLabel.setText(_translate("AddPurchase", "Email Address"))
        self.contactLabel.setText(_translate("AddPurchase", "Contact Number"))
        self.addressLabel.setText(_translate("AddPurchase", "Address"))
        self.countryLabel.setText(_translate("AddPurchase", "Country"))
        self.totalLabel.setText(_translate("AddPurchase", "Total Amount"))
        self.orderDateLabel.setText(_translate("AddPurchase", "Ordered Date"))
        self.product_Label.setText(_translate("AddPurchase", "Product Name"))
        self.rollsizeLabel.setText(_translate("AddPurchase", "Roll Size"))
        self.quantityLabel.setText(_translate("AddPurchase", "Quantity"))
        self.thicknessLabel.setText(_translate("AddPurchase", "Thickness"))
        self.Cancel.setText(_translate("AddPurchase", "Cancel"))
        self.AddOrder_3.setText(_translate("AddPurchase", "Add Purchase"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPurchase = QtWidgets.QDialog()
    ui = Ui_AddPurchase()
    ui.setupUi(AddPurchase)
    AddPurchase.show()
    sys.exit(app.exec_())
