# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2


class Ui_Dasboard(object): 
    
    def __init__(self):
        # PostgreSQL connection
        self.conn = psycopg2.connect(host="aws-1-ap-northeast-2.pooler.supabase.com", dbname="postgres", 
                                     user="postgres.qtfyvvwktvfviudotoxh", password="isy9KwSEmgbTdbxi", 
                                     port=6543)
        self.cur = self.conn.cursor()

    def show_message(self, title, text):
        """Display a modal error dialog."""
        QtWidgets.QMessageBox.critical(None, title, text)
    
    def fetch_purchases(self):
        try:
            sql = """
            SELECT SUM(PUR_AMOUNT) FROM PURCHASE
            """
            self.cur.execute(sql)
            total_sum = self.cur.fetchone()[0]  # Fetch the count value
            return total_sum
        
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
        
    def display_purchase(self):
        total_sum = self.fetch_purchases()
        return total_sum

    def fetch_sale(self):
        try:
            sql = """
            SELECT SUM(ORD_TOTAL_AMOUNT) FROM ORDERS
            """
            self.cur.execute(sql)
            total_sum = self.cur.fetchone()[0]  # Fetch the count value
            return total_sum
        
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
        
    def display_sale(self):
        total_sum = self.fetch_sale()
        return total_sum

    def fetch_total_sale(self):
        try:
            sql = """
            SELECT COUNT(*) FROM ORDERS
            """
            self.cur.execute(sql)
            total_customers = self.cur.fetchone()[0]  # Fetch the count value
            return total_customers
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
        
    def display_total_sale(self):
        # Fetch total customers
        total_sale = self.fetch_total_sale()      
        return total_sale
    
    def fetch_total_purchase(self):
        try:
            sql = """
            SELECT COUNT(*) FROM PURCHASE
            """
            self.cur.execute(sql)
            total_customers = self.cur.fetchone()[0]  # Fetch the count value
            return total_customers
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
        
    def display_total_purchase(self):
        # Fetch total customers
        total_purchase = self.fetch_total_purchase()      
        return total_purchase


    def fetch_total_supplier(self):
        try:
            sql = """
            SELECT COUNT(*) FROM SUPPLIER
            """
            self.cur.execute(sql)
            total_customers = self.cur.fetchone()[0]  # Fetch the count value
            return total_customers
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
        
    def display_total_supplier(self):
        # Fetch total customers
        total_supplier = self.fetch_total_supplier()      
        return total_supplier

    def fetch_total_customers(self):
        try:
            sql = """
            SELECT COUNT(*) FROM CUSTOMER
            """
            self.cur.execute(sql)
            total_customers = self.cur.fetchone()[0]  # Fetch the count value
            return total_customers
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching total customers: {e}")
            return 0  # Return 0 or handle error case
    
    def display_total_customers(self):
        # Fetch total customers
        total_customers = self.fetch_total_customers()      
        return total_customers
    
    def fetch_customer(self):
        try:
            sql = """
            SELECT CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME, ORDERS.ORD_TYPE_PRODUCT, ORDERS.ORD_TOTAL_AMOUNT
            FROM CUSTOMER
            INNER JOIN ORDERS ON CUSTOMER.CUS_CODE = ORDERS.CUS_CODE
            """
            self.cur.execute(sql)
            return self.cur.fetchall()
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching data from database: {e}")
            return []
        
    def display_recent_customer(self, customers):
        self.tableWidget.setRowCount(len(customers))
        for row_number, customer in enumerate(customers):
            for column_number, data in enumerate(customer):
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                item.setText(str(data))
                self.tableWidget.setItem(row_number, column_number, item)

    def fetch_purchase(self):
        try:
            sql = """
            SELECT PUR_PRODUCT_NAME, PUR_AMOUNT
            FROM PURCHASE
            """
            self.cur.execute(sql)
            return self.cur.fetchall()
        except psycopg2.Error as e:
            self.show_message("Database Error", f"Error fetching data from database: {e}")
            return []
        
    def display_recent_purchase(self, customers):
        self.tableWidget_2.setRowCount(len(customers))
        for row_number, customer in enumerate(customers):
            for column_number, data in enumerate(customer):
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                item.setText(str(data))
                self.tableWidget_2.setItem(row_number, column_number, item)
    
    def show_purchase(self):
        from PurchaseView import Ui_PurchaseView
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_PurchaseView()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()
       
    def order(self):
        from Order import Ui_Order_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Order_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def inventory(self):
        from Inventory import Ui_Inventory_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Inventory_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()


    def purchase(self):
        from PurchaseView import Ui_PurchaseView
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_PurchaseView()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def customer(self):
        from Customer import Ui_Customer_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Customer_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def profile(self):
        from Profile import Ui_Profile_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Profile_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()
        
    def show_message(self, title, text):
        """Display a modal error dialog."""
        QtWidgets.QMessageBox.critical(None, title, text)

    def setupUi(self, Dasboard):
        Dasboard.setObjectName("Dasboard")
        Dasboard.resize(975, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dasboard.sizePolicy().hasHeightForWidth())
        Dasboard.setSizePolicy(sizePolicy)
        Dasboard.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(Dasboard)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavbarFrame = QtWidgets.QFrame(self.centralwidget)
        self.NavbarFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavbarFrame.sizePolicy().hasHeightForWidth())
        self.NavbarFrame.setSizePolicy(sizePolicy)
        self.NavbarFrame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.NavbarFrame.setStyleSheet("QPushButton {\n"
"    min-width: 100px; \n"
"    max-width: 150px;\n"
"    min-height: 40px;\n"
"    max-height: 35px;\n"
"    font-size:12px;\n"
"    border: 2px solid #8f8f91; \n"
"    border-radius: 10px;\n"
"    background-color: #d8d8d8; \n"
"    min-width: 80px; \n"
"    min-height: 30px; \n"
"    padding: 5px; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"}\n"
"")
        self.NavbarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NavbarFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.NavbarFrame.setObjectName("NavbarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.NavbarFrame)
        self.horizontalLayout.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Logo = QtWidgets.QLabel(self.NavbarFrame)
        self.Logo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(55, 55))
        self.Logo.setMaximumSize(QtCore.QSize(55, 55))
        self.Logo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Logo.setAutoFillBackground(False)
        self.Logo.setStyleSheet("")
        self.Logo.setText("")
        self.Logo.setTextFormat(QtCore.Qt.RichText)
        self.Logo.setPixmap(QtGui.QPixmap("static/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setWordWrap(False)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout.addWidget(self.Logo)
        self.tarp = QtWidgets.QLabel(self.NavbarFrame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tarp.setFont(font)
        self.tarp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tarp.setAutoFillBackground(False)
        self.tarp.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: #CD2E2E;")
        self.tarp.setObjectName("tarp")
        self.horizontalLayout.addWidget(self.tarp)
        self.Inventory = QtWidgets.QPushButton(self.NavbarFrame)
        self.Inventory.clicked.connect(self.inventory)
        self.Inventory.clicked.connect(Dasboard.close)
        self.Inventory.setMinimumSize(QtCore.QSize(94, 44))
        self.Inventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Inventory.setStyleSheet("font-size:12px;\n"
"color: white;\n"
"border: 2px solid #8f8f91;\n"
"background-color: #d8d8d8;\n"
"color: black;\n"
"")
        self.Inventory.setObjectName("Inventory")
        self.horizontalLayout.addWidget(self.Inventory)
        self.Order = QtWidgets.QPushButton(self.NavbarFrame)
        self.Order.clicked.connect(self.order)
        self.Order.clicked.connect(Dasboard.close)
        self.Order.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Order.setStyleSheet("font-size:12px;")
        self.Order.setObjectName("Order")
        self.horizontalLayout.addWidget(self.Order)
        self.Purchase = QtWidgets.QPushButton(self.NavbarFrame)
        self.Purchase.clicked.connect(self.purchase)
        self.Purchase.clicked.connect(Dasboard.close)
        self.Purchase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Purchase.setStyleSheet("font-size:12px;")
        self.Purchase.setObjectName("Purchase")
        self.horizontalLayout.addWidget(self.Purchase)
        self.Customer = QtWidgets.QPushButton(self.NavbarFrame)
        self.Customer.clicked.connect(self.customer)
        self.Customer.clicked.connect(Dasboard.close)
        self.Customer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Customer.setStyleSheet("font-size:12px;")
        self.Customer.setObjectName("Customer")
        self.horizontalLayout.addWidget(self.Customer)
        self.Profile = QtWidgets.QPushButton(self.NavbarFrame)
        self.Profile.clicked.connect(self.profile)
        self.Profile.clicked.connect(Dasboard.close)
        self.Profile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Profile.setStyleSheet("font-size:12px;")
        self.Profile.setObjectName("Profile")
        self.horizontalLayout.addWidget(self.Profile)
        self.verticalLayout.addWidget(self.NavbarFrame)
        self.TableContainer = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableContainer.sizePolicy().hasHeightForWidth())
        self.TableContainer.setSizePolicy(sizePolicy)
        self.TableContainer.setMinimumSize(QtCore.QSize(0, 2))
        self.TableContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TableContainer.setAutoFillBackground(False)
        self.TableContainer.setStyleSheet("background-color: #FAFAFA;\n"
"width: 100vw;")
        self.TableContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TableContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TableContainer.setObjectName("TableContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TableContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label = QtWidgets.QFrame(self.TableContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setStyleSheet("border-top: 5px solid #CD2E2E;\n"
"border-bottom: 5px solid #CD2E2E;\n"
"\n"
"")
        self.Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Label.setObjectName("Label")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Label)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CustomersCount = QtWidgets.QFrame(self.Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomersCount.sizePolicy().hasHeightForWidth())
        self.CustomersCount.setSizePolicy(sizePolicy)
        self.CustomersCount.setMinimumSize(QtCore.QSize(140, 80))
        self.CustomersCount.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.CustomersCount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CustomersCount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CustomersCount.setObjectName("CustomersCount")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CustomersCount)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.CustomersCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.CustomersCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.CustomersCount)
        self.SuppliersCount = QtWidgets.QFrame(self.Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppliersCount.sizePolicy().hasHeightForWidth())
        self.SuppliersCount.setSizePolicy(sizePolicy)
        self.SuppliersCount.setMinimumSize(QtCore.QSize(140, 70))
        self.SuppliersCount.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.SuppliersCount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SuppliersCount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SuppliersCount.setObjectName("SuppliersCount")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SuppliersCount)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.SuppliersCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.SuppliersCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2.addWidget(self.SuppliersCount)
        self.PurchaseCount = QtWidgets.QFrame(self.Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PurchaseCount.sizePolicy().hasHeightForWidth())
        self.PurchaseCount.setSizePolicy(sizePolicy)
        self.PurchaseCount.setMinimumSize(QtCore.QSize(140, 70))
        self.PurchaseCount.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.PurchaseCount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PurchaseCount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PurchaseCount.setObjectName("PurchaseCount")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.PurchaseCount)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.PurchaseCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.PurchaseCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.PurchaseCount)
        self.SalesCount = QtWidgets.QFrame(self.Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SalesCount.sizePolicy().hasHeightForWidth())
        self.SalesCount.setSizePolicy(sizePolicy)
        self.SalesCount.setMinimumSize(QtCore.QSize(140, 70))
        self.SalesCount.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.SalesCount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SalesCount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SalesCount.setObjectName("SalesCount")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SalesCount)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.SalesCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.SalesCount)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_2.addWidget(self.SalesCount)
        self.verticalLayout_2.addWidget(self.Label)
        self.DataFrame = QtWidgets.QFrame(self.TableContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFrame.sizePolicy().hasHeightForWidth())
        self.DataFrame.setSizePolicy(sizePolicy)
        self.DataFrame.setStyleSheet("background-color: white;")
        self.DataFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.DataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataFrame.setObjectName("DataFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.DataFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.DataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.CustomersCount_2 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomersCount_2.sizePolicy().hasHeightForWidth())
        self.CustomersCount_2.setSizePolicy(sizePolicy)
        self.CustomersCount_2.setMinimumSize(QtCore.QSize(50, 80))
        self.CustomersCount_2.setMaximumSize(QtCore.QSize(1000, 150))
        self.CustomersCount_2.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.CustomersCount_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CustomersCount_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CustomersCount_2.setObjectName("CustomersCount_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CustomersCount_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.CustomersCount_2)
        self.label_13.setMinimumSize(QtCore.QSize(20, 20))
        self.label_13.setMaximumSize(QtCore.QSize(40, 50))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/static/static/cash.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.frame_5 = QtWidgets.QFrame(self.CustomersCount_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_6.addWidget(self.CustomersCount_2)
        self.CustomersCount_3 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomersCount_3.sizePolicy().hasHeightForWidth())
        self.CustomersCount_3.setSizePolicy(sizePolicy)
        self.CustomersCount_3.setMinimumSize(QtCore.QSize(50, 80))
        self.CustomersCount_3.setMaximumSize(QtCore.QSize(1000, 150))
        self.CustomersCount_3.setStyleSheet("border-top: none;\n"
"border-bottom: none;\n"
"background-color: #FFE664;\n"
"border-radius: 10px;")
        self.CustomersCount_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CustomersCount_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CustomersCount_3.setObjectName("CustomersCount_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CustomersCount_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.CustomersCount_3)
        self.label_14.setMinimumSize(QtCore.QSize(20, 20))
        self.label_14.setMaximumSize(QtCore.QSize(40, 50))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/static/static/delivery.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.frame_6 = QtWidgets.QFrame(self.CustomersCount_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.horizontalLayout_6.addWidget(self.CustomersCount_3)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.DataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.AddProduct = QtWidgets.QPushButton(self.frame_7)
        self.AddProduct.clicked.connect(self.show_purchase)
        self.AddProduct.clicked.connect(Dasboard.close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddProduct.sizePolicy().hasHeightForWidth())
        self.AddProduct.setSizePolicy(sizePolicy)
        self.AddProduct.setMinimumSize(QtCore.QSize(130, 34))
        self.AddProduct.setMaximumSize(QtCore.QSize(130, 34))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AddProduct.setFont(font)
        self.AddProduct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddProduct.setStyleSheet("font-size:12px;\n"
"border: 2px solid #E08028; \n"
"border-radius: 10px;\n"
"background-color: #E08028; \n"
"padding: 5px; \n"
"color: white; \n"
"font-weight: bold; frf")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/static/static/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddProduct.setIcon(icon)
        self.AddProduct.setIconSize(QtCore.QSize(20, 20))
        self.AddProduct.setObjectName("AddProduct")
        self.horizontalLayout_7.addWidget(self.AddProduct)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.tableWidget_2)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.DataFrame)
        self.verticalLayout.addWidget(self.TableContainer)
        Dasboard.setCentralWidget(self.centralwidget)

        customer = self.fetch_customer()
        self.display_recent_customer(customer)

        purchase = self.fetch_purchase()
        self.display_recent_purchase(purchase)

        self.retranslateUi(Dasboard)
        QtCore.QMetaObject.connectSlotsByName(Dasboard)

    def retranslateUi(self, Dasboard):
        _translate = QtCore.QCoreApplication.translate
        Dasboard.setWindowTitle(_translate("Dasboard", "MainWindow"))
        self.tarp.setText(_translate("Dasboard", "TARPAULIN PRINTING SERVICES"))
        self.Inventory.setText(_translate("Dasboard", "Inventory"))
        self.Order.setText(_translate("Dasboard", "Orders"))
        self.Purchase.setText(_translate("Dasboard", "Purchases"))
        self.Customer.setText(_translate("Dasboard", "Customers"))
        self.Profile.setText(_translate("Dasboard", "Profile"))
        self.label.setText(_translate("Dasboard", f"{self.display_total_customers()}"))
        self.label_2.setText(_translate("Dasboard", "Customers"))
        self.label_3.setText(_translate("Dasboard", f"{self.display_total_supplier()}"))
        self.label_4.setText(_translate("Dasboard", "Suppliers"))
        self.label_5.setText(_translate("Dasboard", f"{self.display_total_purchase()}"))
        self.label_6.setText(_translate("Dasboard", "Purchases"))
        self.label_7.setText(_translate("Dasboard", f"{self.display_total_sale()}"))
        self.label_8.setText(_translate("Dasboard", "Sales Count"))
        self.label_15.setText(_translate("Dasboard", "Last Transactions"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dasboard", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dasboard", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dasboard", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dasboard", "Amount"))
        self.label_10.setText(_translate("Dasboard", "Total Sales"))
        self.label_9.setText(_translate("Dasboard", f"{self.display_sale()}"))
        self.label_11.setText(_translate("Dasboard", "Total Purchases"))
        self.label_12.setText(_translate("Dasboard", f"{self.display_purchase()}"))
        self.label_16.setText(_translate("Dasboard", "Recent Purchases"))
        self.AddProduct.setText(_translate("Dasboard", " View All"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dasboard", "Products"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dasboard", "Price"))
        
import font_rc
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dasboard = QtWidgets.QMainWindow()
    ui = Ui_Dasboard()
    ui.setupUi(Dasboard)
    Dasboard.show()
    sys.exit(app.exec_())
