# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickable import ClickableLabel 
import psycopg2

class Ui_Profile_2(object):
    
    def __init__(self):
        # PostgreSQL connection
        self.conn = psycopg2.connect(host="aws-0-ap-southeast-1.pooler.supabase.com", dbname="postgres", 
                                     user="postgres.oxzprkjuxnjgnfihweyj", password="Milliondollarbaby123", 
                                     port=6543)
        self.cur = self.conn.cursor()

    def fetch_user_details(self, username):
        sql = "SELECT ADMIN_NAME, ADMIN_EMAIL, ADMIN_USER, ADMIN_PMNT_ADD, ADMIN_ZIP, ADMIN_PRSNT_ADD, ADMIN_CITY, ADMIN_COUNTRY FROM ADMIN WHERE ADMIN_USER = %s"
        self.cur.execute(sql, (username,))
        return self.cur.fetchone()
    
    def back_dashboard(self):
        from Dashboard import Ui_Dasboard
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Dasboard()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()
            
    def logout(self):
        from Login import Ui_Login
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()
    
    def order(self):
        from Order import Ui_Order_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Order_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def inventory(self):
        from Inventory import Ui_Inventory_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Inventory_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def purchase(self):
        from PurchaseView import Ui_PurchaseView
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_PurchaseView()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def customer(self):
        from Customer import Ui_Customer_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Customer_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def profile(self):
        from Profile import Ui_Profile_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Profile_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def setupUi(self, Profile_2):
        Profile_2.setObjectName("Profile_2")
        Profile_2.resize(975, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Profile_2.sizePolicy().hasHeightForWidth())
        Profile_2.setSizePolicy(sizePolicy)
        Profile_2.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(Profile_2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavbarFrame = QtWidgets.QFrame(self.centralwidget)
        self.NavbarFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavbarFrame.sizePolicy().hasHeightForWidth())
        self.NavbarFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NavbarFrame.setFont(font)
        self.NavbarFrame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.NavbarFrame.setStyleSheet("QPushButton {\n"
"    min-width: 100px; \n"
"    max-width: 150px;\n"
"    min-height: 40px;\n"
"    max-height: 35px;\n"
"    font-size:12px;\n"
"    border: 2px solid #8f8f91; \n"
"    border-radius: 10px;\n"
"    background-color: #d8d8d8; \n"
"    min-width: 80px; \n"
"    min-height: 30px; \n"
"    padding: 5px; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"}\n"
"")
        self.NavbarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NavbarFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.NavbarFrame.setObjectName("NavbarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.NavbarFrame)
        self.horizontalLayout.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Logo = QtWidgets.QLabel(self.NavbarFrame)
        self.Logo.setEnabled(True)
        self.Logo.setFixedSize(150,100)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Logo.setFont(font)
        self.Logo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Logo.setAutoFillBackground(False)
        self.Logo.setStyleSheet("")
        self.Logo.setText("")
        self.Logo.setTextFormat(QtCore.Qt.RichText)
        self.Logo.setPixmap(QtGui.QPixmap("static/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setWordWrap(False)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout.addWidget(self.Logo)
        self.tarp = ClickableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tarp.setFont(font)
        self.tarp.setAutoFillBackground(False)
        self.tarp.setStyleSheet("font: 75 12pt 'Georgia';\n"
                                "color: #CD2E2E;")
        self.tarp.setObjectName("tarp")
        self.horizontalLayout.addWidget(self.tarp)
        self.tarp.clicked.connect(self.back_dashboard)
        self.tarp.clicked.connect(Profile_2.close)
        self.Inventory = QtWidgets.QPushButton(self.NavbarFrame)
        self.Inventory.clicked.connect(self.inventory)
        self.Inventory.clicked.connect(Profile_2.close)
        self.Inventory.setMinimumSize(QtCore.QSize(94, 44))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Inventory.setFont(font)
        self.Inventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Inventory.setStyleSheet("font-size:12px;\n"
"\n"
"")
        self.Inventory.setObjectName("Inventory")
        self.horizontalLayout.addWidget(self.Inventory)
        self.Order = QtWidgets.QPushButton(self.NavbarFrame)
        self.Order.clicked.connect(self.order)
        self.Order.clicked.connect(Profile_2.close)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Order.setFont(font)
        self.Order.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Order.setStyleSheet("font-size:12px;\n"
"")
        self.Order.setObjectName("Order")
        self.horizontalLayout.addWidget(self.Order)
        self.Purchase = QtWidgets.QPushButton(self.NavbarFrame)
        self.Purchase.clicked.connect(self.purchase)
        self.Purchase.clicked.connect(Profile_2.close)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Purchase.setFont(font)
        self.Purchase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Purchase.setStyleSheet("font-size:12px;\n"
"")
        self.Purchase.setObjectName("Purchase")
        self.horizontalLayout.addWidget(self.Purchase)
        self.Customer = QtWidgets.QPushButton(self.NavbarFrame)
        self.Customer.clicked.connect(self.customer)
        self.Customer.clicked.connect(Profile_2.close)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Customer.setFont(font)
        self.Customer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Customer.setStyleSheet("font-size:12px;")
        self.Customer.setObjectName("Customer")
        self.horizontalLayout.addWidget(self.Customer)
        self.Profile = QtWidgets.QPushButton(self.NavbarFrame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Profile.setFont(font)
        self.Profile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Profile.setStyleSheet("font-size:12px;\n"
"color: white;\n"
"border: 2px solid #CD2E2E;\n"
"background-color: #CD2E2E;")
        self.Profile.setObjectName("Profile")
        self.horizontalLayout.addWidget(self.Profile)
        self.verticalLayout.addWidget(self.NavbarFrame)
        self.TableContainer = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableContainer.sizePolicy().hasHeightForWidth())
        self.TableContainer.setSizePolicy(sizePolicy)
        self.TableContainer.setMinimumSize(QtCore.QSize(0, 2))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TableContainer.setFont(font)
        self.TableContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TableContainer.setAutoFillBackground(False)
        self.TableContainer.setStyleSheet("background-color: #FAFAFA;\n"
"width: 100vw;")
        self.TableContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TableContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TableContainer.setObjectName("TableContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TableContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DataFrame = QtWidgets.QFrame(self.TableContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFrame.sizePolicy().hasHeightForWidth())
        self.DataFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DataFrame.setFont(font)
        self.DataFrame.setStyleSheet("background-color: #F9EDED;")
        self.DataFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.DataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataFrame.setObjectName("DataFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DataFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.DataFrame)
        self.frame.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"}    ")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(758, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Inventory_2 = QtWidgets.QPushButton(self.frame)
        self.Inventory_2.clicked.connect(self.logout)
        self.Inventory_2.clicked.connect(Profile_2.close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Inventory_2.sizePolicy().hasHeightForWidth())
        self.Inventory_2.setSizePolicy(sizePolicy)
        self.Inventory_2.setMinimumSize(QtCore.QSize(94, 44))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Inventory_2.setFont(font)
        self.Inventory_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Inventory_2.setStyleSheet("font-size:12px;\n"
"min-width: 100px; \n"
"max-width: 150px;\n"
"min-height: 40px;\n"
"max-height: 35px;\n"
"border: 2px solid #8f8f91; \n"
"border-radius: 10px;\n"
"background-color: #d8d8d8; \n"
"min-width: 80px; \n"
"min-height: 30px; \n"
"padding: 5px; \n"
"color: black; \n"
"font-weight: bold; ")
        self.Inventory_2.setObjectName("Inventory_2")
        self.horizontalLayout_2.addWidget(self.Inventory_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.DataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(51, 46))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/static/static/R.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)

        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setStyleSheet("QLabel{\n"
"    font-size: 15px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setContentsMargins(400, 50, 20, 20)
        self.formLayout.setHorizontalSpacing(150)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.frame_4)
        self.label_name.setMinimumSize(QtCore.QSize(200, 0))
        self.label_name.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.labe_username = QtWidgets.QLabel(self.frame_4)
        self.labe_username.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labe_username)
        self.name = QtWidgets.QLineEdit(self.frame_4)
        self.name.setEnabled(False)
        self.name.setFixedSize(QtCore.QSize(250, 45))
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.name)
        self.username = QtWidgets.QLineEdit(self.frame_4)
        self.username.setEnabled(False)
        self.username.setFixedSize(QtCore.QSize(250, 45))
        self.username.setObjectName("username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username)
        self.label_email = QtWidgets.QLabel(self.frame_4)
        self.label_email.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.label_password = QtWidgets.QLabel(self.frame_4)
        self.label_password.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_password)
        self.email = QtWidgets.QLineEdit(self.frame_4)
        self.email.setEnabled(False)
        self.email.setFixedSize(QtCore.QSize(250, 45))
        self.email.setObjectName("email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.email)
        self.password = QtWidgets.QLineEdit(self.frame_4)
        self.password.setEnabled(False)
        self.password.setFixedSize(QtCore.QSize(250, 45))
        self.password.setObjectName("password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.label_birth = QtWidgets.QLabel(self.frame_4)
        self.label_birth.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_birth)
        self.label_present_address = QtWidgets.QLabel(self.frame_4)
        self.label_present_address.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_present_address)
        self.date_of_birth = QtWidgets.QLineEdit(self.frame_4)
        self.date_of_birth.setEnabled(False)
        self.date_of_birth.setFixedSize(QtCore.QSize(250, 45))
        self.date_of_birth.setObjectName("date_of_birth")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.date_of_birth)
        self.present_address = QtWidgets.QLineEdit(Profile_2)
        self.present_address.setEnabled(False)
        self.present_address.setFixedSize(QtCore.QSize(250, 45))
        self.present_address.setObjectName("present_address")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.present_address)
        self.label_permanent_addresss = QtWidgets.QLabel(self.frame_4)
        self.label_permanent_addresss.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_permanent_addresss)
        self.label_city = QtWidgets.QLabel(self.frame_4)
        self.label_city.setObjectName("label_15")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_city)
        self.permanent_address = QtWidgets.QLineEdit(self.frame_4)
        self.permanent_address.setEnabled(False)
        self.permanent_address.setFixedSize(QtCore.QSize(250, 45))
        self.permanent_address.setObjectName("permanent_address")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.permanent_address)
        self.city = QtWidgets.QLineEdit(self.frame_4)
        self.city.setEnabled(False)
        self.city.setFixedSize(QtCore.QSize(250, 45))
        self.city.setObjectName("city")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.city)
        self.label_postal = QtWidgets.QLabel(self.frame_4)
        self.label_postal.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_postal)
        self.label_country = QtWidgets.QLabel(self.frame_4)
        self.label_country.setObjectName("label_16")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_country)
        self.postal = QtWidgets.QLineEdit(self.frame_4)
        self.postal.setEnabled(False)
        self.postal.setFixedSize(QtCore.QSize(250, 45))
        self.postal.setObjectName("postal")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.postal)
        self.country = QtWidgets.QLineEdit(self.frame_4)
        self.country.setEnabled(False)
        self.country.setFixedSize(QtCore.QSize(250, 45))
        self.country.setObjectName("country")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.country)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.DataFrame)
        self.verticalLayout.addWidget(self.TableContainer)
        Profile_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Profile_2)
        QtCore.QMetaObject.connectSlotsByName(Profile_2)
    
        username = 'test'
        user_details = self.fetch_user_details(username)

        # Populate user details into QLineEdit fields
        if user_details:
            self.username.setText(user_details[2])  # Username
            self.name.setText(user_details[0])  # Full Name
            self.email.setText(user_details[1])  # Email
            self.permanent_address.setText(user_details[3])  # Permanent Address
            self.postal.setText(user_details[4])  # ZIP Code
            self.present_address.setText(user_details[5])  # Present Address
            self.city.setText(user_details[6])  # City
            self.country.setText(user_details[7])  # Country

    def retranslateUi(self, Profile_2):
        _translate = QtCore.QCoreApplication.translate
        Profile_2.setWindowTitle(_translate("Profile_2", "MainWindow"))
        self.tarp.setText(_translate("Profile_2", "TARPAULIN PRINTING SERVICES"))
        self.Inventory.setText(_translate("Profile_2", "Inventory"))
        self.Order.setText(_translate("Profile_2", "Orders"))
        self.Purchase.setText(_translate("Profile_2", "Purchases"))
        self.Customer.setText(_translate("Profile_2", "Customers"))
        self.Profile.setText(_translate("Profile_2", "Profile"))
        self.Inventory_2.setText(_translate("Profile_2", "Logout"))
        self.label_name.setText(_translate("Profile_2", "Busssines Name"))
        self.labe_username.setText(_translate("Profile_2", "Social Media"))
        self.label_email.setText(_translate("Profile_2", "Email"))
        self.label_password.setText(_translate("Profile_2", "Opening Hour"))
        self.label_birth.setText(_translate("Profile_2", "Contact Number"))
        self.label_present_address.setText(_translate("Profile_2", "Present Address"))
        self.label_permanent_addresss.setText(_translate("Profile_2", "Permanent Address"))
        self.label_city.setText(_translate("Profile_2", "City"))
        self.label_postal.setText(_translate("Profile_2", "Postal Code"))
        self.label_country.setText(_translate("Profile_2", "Country"))
import font_rc
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Profile_2 = QtWidgets.QMainWindow()
    ui = Ui_Profile_2()
    ui.setupUi(Profile_2)
    Profile_2.show()
    sys.exit(app.exec_())
