# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateOrder(object):
    def setupUi(self, UpdateOrder):
        UpdateOrder.setObjectName("UpdateOrder")
        UpdateOrder.resize(640, 480)
        self.frame = QtWidgets.QFrame(UpdateOrder)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel#AddOrder{\n"
"    font-size: 25px;\n"
"}\n"
"QLineEdit{\n"
"    width: 200px;\n"
"    font-size: 15px;\n"
"}\n"
"QPushButton#Cancel{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #202020;\n"
"}\n"
"QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #CD2E2E;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(35, 30, 156, 26))
        self.AddOrder.setObjectName("AddOrder")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 120, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 76, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 175, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 155, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 280, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 76, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(405, 145, 86, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(405, 235, 113, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(405, 215, 47, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_13.setGeometry(QtCore.QRect(405, 165, 113, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(354, 360, 96, 31))
        self.Cancel.setObjectName("Cancel")
        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.setGeometry(QtCore.QRect(475, 360, 91, 31))
        self.AddOrder_3.setObjectName("AddOrder_3")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(80, 205, 76, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 225, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")

        self.retranslateUi(UpdateOrder)
        QtCore.QMetaObject.connectSlotsByName(UpdateOrder)

    def retranslateUi(self, UpdateOrder):
        _translate = QtCore.QCoreApplication.translate
        UpdateOrder.setWindowTitle(_translate("UpdateOrder", "Dialog"))
        self.AddOrder.setText(_translate("UpdateOrder", "Update Order"))
        self.label_2.setText(_translate("UpdateOrder", "Email Address"))
        self.label_3.setText(_translate("UpdateOrder", "Contact Number"))
        self.label_4.setText(_translate("UpdateOrder", "Total Amount"))
        self.label_10.setText(_translate("UpdateOrder", "Completion Date"))
        self.label_12.setText(_translate("UpdateOrder", "Quantity"))
        self.Cancel.setText(_translate("UpdateOrder", "Cancel"))
        self.AddOrder_3.setText(_translate("UpdateOrder", "Update Order"))
        self.label_14.setText(_translate("UpdateOrder", "Address"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateOrder = QtWidgets.QDialog()
    ui = Ui_UpdateOrder()
    ui.setupUi(UpdateOrder)
    UpdateOrder.show()
    sys.exit(app.exec_())
