# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
from PyQt5.QtWidgets import QMessageBox


class Ui_UpdateProduct(object):

    def __init__(self):
        # PostgreSQL connection        
        self.conn = psycopg2.connect(host="aws-0-ap-southeast-1.pooler.supabase.com", dbname="postgres", user="postgres.oxzprkjuxnjgnfihweyj", 
                                     password="Milliondollarbaby123", port=6543)
        self.cur = self.conn.cursor()

    def save_data(self):
        # Get data from UI elements
        prod_name = self.lineEdit.text().strip()
        prod_price = self.lineEdit_2.text().strip()
        prod_quantity = self.lineEdit_3.text().strip()
        prod_rollSize = self.lineEdit_4.text().strip()
        prod_thickness = self.lineEdit_14.text().strip()

        # Validate input data
        if not (prod_name and prod_price and prod_quantity):
            self.show_message("Error", "Please fill all the fields.")
            return

        try:
            # Check if product exists and get its ID
            sql_get_product_id = "SELECT PROD_ID FROM PRODUCT WHERE PROD_NAME = %s"
            self.cur.execute(sql_get_product_id, (prod_name,))
            product_id_result = self.cur.fetchone()

            if product_id_result is None:
                self.show_message("Error", "Selected product does not exist.")
                return

            product_id = product_id_result[0]

            # Update product details
            sql_update_product = """
            UPDATE PRODUCT 
            SET PROD_PRICE = %s, PROD_QUANTITY = %s, PROD_ROLL_SIZE = %s, PROD_THICKNESS = %s
            WHERE PROD_ID = %s
            """
            self.cur.execute(sql_update_product, (prod_price, prod_quantity, prod_rollSize, prod_thickness, product_id))
            self.conn.commit()

            self.show_message("Success", "Product updated successfully.")
        except psycopg2.Error as e:
            self.conn.rollback()  # Roll back transaction on error
            error_message = f"Error saving data: {e.pgcode} - {e.pgerror}"
            self.show_message("Error", error_message) 

    def show_message(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Information)
        msg.exec_()

    def setupUi(self, UpdateProduct):
        UpdateProduct.setObjectName("UpdateProduct")
        UpdateProduct.resize(640, 480)
        UpdateProduct.setFixedSize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        UpdateProduct.setSizePolicy(sizePolicy)

        self.frame = QtWidgets.QFrame(UpdateProduct)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel#AddOrder{\n"
"    font-size: 25px;\n"
"}\n"
"QLineEdit{\n"
"    width: 200px;\n"
"}\n"
"QPushButton#Cancel{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #202020;\n"
"}\n"
"QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #CD2E2E;\n"
"}\n"
"QPushButton#Image{    \n"
"    color: black;\n"
"    background-color: dirty white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(35, 30, 191, 26))
        self.AddOrder.setObjectName("AddOrder")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 100, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 120, 111, 20))
        self.lineEdit.setMaxLength(300)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 175, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 155, 76, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 230, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 210, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 335, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 315, 76, 16))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(400, 70, 66, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(400, 130, 81, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(400, 205, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(400, 185, 86, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_12.setGeometry(QtCore.QRect(400, 150, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.clicked.connect(UpdateProduct.close)
        self.Cancel.setGeometry(QtCore.QRect(354, 360, 96, 31))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.clicked.connect(self.save_data)
        self.AddOrder_3.clicked.connect(UpdateProduct.close)
        self.AddOrder_3.setGeometry(QtCore.QRect(475, 360, 91, 31))
        self.AddOrder_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddOrder_3.setObjectName("AddOrder_3")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(80, 260, 76, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 280, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(400, 95, 111, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Image = QtWidgets.QPushButton(self.frame)
        self.Image.setGeometry(QtCore.QRect(365, 240, 191, 96))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Image.setIcon(icon)
        self.Image.setIconSize(QtCore.QSize(20, 20))
        self.Image.setObjectName("Image")
        self.Cancel.raise_()
        self.AddOrder_3.raise_()

        self.retranslateUi(UpdateProduct)
        QtCore.QMetaObject.connectSlotsByName(UpdateProduct)

    def retranslateUi(self, UpdateProduct):
        _translate = QtCore.QCoreApplication.translate
        UpdateProduct.setWindowTitle(_translate("UpdateProduct", "Dialog"))
        self.AddOrder.setText(_translate("UpdateProduct", "Update Product"))
        self.label.setText(_translate("UpdateProduct", "Product Name"))
        self.label_2.setText(_translate("UpdateProduct", "Price"))
        self.label_3.setText(_translate("UpdateProduct", "Quantity"))
        self.label_4.setText(_translate("UpdateProduct", "Roll Size"))
        self.label_9.setText(_translate("UpdateProduct", "Category"))
        self.label_10.setText(_translate("UpdateProduct", "Type of Product"))
        self.label_12.setText(_translate("UpdateProduct", "Quantity per roll"))
        self.Cancel.setText(_translate("UpdateProduct", "Cancel"))
        self.AddOrder_3.setText(_translate("UpdateProduct", "Update Product"))
        self.label_14.setText(_translate("UpdateProduct", "Thickness"))
        self.comboBox.setItemText(0, _translate("UpdateProduct", "Large Format Tarpulin "))
        self.comboBox.setItemText(1, _translate("UpdateProduct", "Vinyl Sticker Printin"))
        self.comboBox.setItemText(2, _translate("UpdateProduct", "Laser Printing for papers and Stickers"))
        self.comboBox.setItemText(3, _translate("UpdateProduct", "T-shirt printing "))
        self.Image.setText(_translate("UpdateProduct", "Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateProduct = QtWidgets.QDialog()
    ui = Ui_UpdateProduct()
    ui.setupUi(UpdateProduct)
    UpdateProduct.show()
    sys.exit(app.exec_())
