# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import  pyqtSignal, QObject
from PyQt5.QtWidgets import QMessageBox
import psycopg2

class Ui_UpdateCustomer(QObject):
    customer_info_updated = pyqtSignal(str, str, str, str, str)  # Define a signal with updated customer information

    def customer(self):
        from Customer import Ui_Customer_2
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_Customer_2()
        self.ui.setupUi(self.window2)
        self.window2.showMaximized()

    def update_customer_info(self):
        from psycopg2 import IntegrityError
        # Get the new information entered by the user
        new_first_name = self.lineEdit_2.text()
        new_last_name = self.lineEdit_3.text()
        new_phone = self.lineEdit_4.text()
        new_address = self.lineEdit_13.text()
        new_email = self.lineEdit_14.text()

        # Check if any of the fields are empty
        if new_first_name or new_last_name or new_phone or new_address or new_email:
            try:
                # Establish a connection to the PostgreSQL database
                conn = psycopg2.connect(host="aws-0-ap-southeast-1.pooler.supabase.com", dbname="postgres", user="postgres.oxzprkjuxnjgnfihweyj",
                                        password="Milliondollarbaby123", port=6543)
                cur = conn.cursor()

                # Update the customer information in the database
                sql = """
                UPDATE CUSTOMER
                SET CUS_FNAME = %s, CUS_LNAME = %s, CUS_PHONE = %s, CUS_ADDRESS = %s
                WHERE CUS_EMAIL = %s
                """
                cur.execute(sql, (new_first_name, new_last_name, new_phone, new_address, new_email))
                conn.commit()

                print("Customer information updated successfully!")

                # Close the cursor and connection
                cur.close()
                conn.close()

            except IntegrityError as e:
                conn.rollback()  # Rollback the transaction to handle the error gracefully
                print(f"IntegrityError: {e}")

                # Handle the unique constraint violation here (merge data, update other fields, etc.)
                # Example:
                # You can choose to update other fields when the email already exists
                update_sql = """
                UPDATE CUSTOMER
                SET CUS_FNAME = %s, CUS_LNAME = %s, CUS_PHONE = %s, CUS_ADDRESS = %s
                WHERE CUS_EMAIL = %s
                """
                cur.execute(update_sql, (new_first_name, new_last_name, new_phone, new_address, new_email))
                conn.commit()

                print("Customer information updated despite duplicate email.")

                # Close the cursor and connection
                cur.close()
                conn.close()

            except psycopg2.Error as e:
                print(f"Error updating customer information: {e}")

        else:
            print("No changes made. Retaining current customer information.")

        self.customer_info_updated.emit(new_first_name, new_last_name, new_phone, new_address, new_email)

    def setupUi(self, UpdateCustomer):
        from Customer import Ui_Customer_2
        UpdateCustomer.setObjectName("UpdateCustomer")
        UpdateCustomer.resize(640, 480)
        UpdateCustomer.setFixedSize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        UpdateCustomer.setSizePolicy(sizePolicy)

        self.frame = QtWidgets.QFrame(UpdateCustomer)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel#AddOrder{\n"
"    font-size: 25px;\n"
"}\n"
"QLineEdit{\n"
"    width: 200px;\n"
"}\n"
"QPushButton#Cancel{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #202020;\n"
"}\n"
"QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #CD2E2E;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AddOrder = QtWidgets.QLabel(self.frame)
        self.AddOrder.setGeometry(QtCore.QRect(35, 30, 191, 26))
        self.AddOrder.setObjectName("AddOrder")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 120, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 76, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 175, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 155, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 280, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 76, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(405, 145, 86, 16))
        self.label_10.setObjectName("label_10")
        
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_13.setGeometry(QtCore.QRect(405, 165, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.clicked.connect(UpdateCustomer.close)       
        self.Cancel.setGeometry(QtCore.QRect(354, 360, 96, 31))
        self.Cancel.setObjectName("Cancel")
        self.AddOrder_3 = QtWidgets.QPushButton(self.frame)
        self.AddOrder_3.clicked.connect(self.update_customer_info)
        self.AddOrder_3.clicked.connect(UpdateCustomer.close)
        self.AddOrder_3.setGeometry(QtCore.QRect(475, 360, 91, 31))
        self.AddOrder_3.setObjectName("AddOrder_3")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(80, 205, 76, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 225, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")

        self.retranslateUi(UpdateCustomer)
        QtCore.QMetaObject.connectSlotsByName(UpdateCustomer)

    def retranslateUi(self, UpdateCustomer):
        _translate = QtCore.QCoreApplication.translate
        UpdateCustomer.setWindowTitle(_translate("UpdateCustomer", "Dialog"))
        self.AddOrder.setText(_translate("UpdateCustomer", "Update Customer"))
        self.label_2.setText(_translate("UpdateCustomer", "First Name"))
        self.label_3.setText(_translate("UpdateCustomer", "Last Name"))
        self.label_4.setText(_translate("UpdateCustomer", "Phone Numer"))
        self.label_10.setText(_translate("UpdateCustomer", "Address"))
        self.Cancel.setText(_translate("UpdateCustomer", "Cancel"))
        self.AddOrder_3.setText(_translate("UpdateCustomer", "Update"))
        self.label_14.setText(_translate("UpdateCustomer", "Email Address"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateCustomer = QtWidgets.QDialog()
    ui = Ui_UpdateCustomer()
    ui.setupUi(UpdateCustomer)
    UpdateCustomer.show()
    sys.exit(app.exec_())
